test_that("the plot page holds the charts, the statistics and the trades", {
  candles <- ParityTinyCandles$new()$frame()
  backtest <- Backtest$new(candles, ParityBuyOnce, cash = 10000)
  statistics <- backtest$run()
  page <- BacktestPlot$new(candles, statistics)$html()
  expect_match(page, "<!doctype html>", fixed = TRUE)
  expect_match(page, "ParityBuyOnce", fixed = TRUE)
  expect_match(page, "Equity Final [$]", fixed = TRUE)
  expect_equal(lengths(regmatches(page, gregexpr("<svg", page, fixed = TRUE))), 2)
  plot_path <- withr::local_tempfile(fileext = ".html")
  backtest$plot(filename = plot_path)
  expect_true(file.exists(plot_path))
  expect_error(backtest$plot(), class = "ValueError")
})
